Cast AbstractControl to FormGroup
error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
<div class="field" *ngIf="form.controls['end'].controls['include'].value">

Signed-off-by: michael sorens <msorens@chef.io>