[A2-798] split partial result update calls for v2 and v2.1 (#467)
* opa: don't share a compiler

Also: simplify module override logic a bit.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* opa: don't include opa.New() in benchmark

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* opa: dedup DumpData{,V2}

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* authz-service/policy_refresher: only refresh IAM v2 XOR v2.1

This should allows us to shave a bit off our policy creation/update
times, by only running what we should need.

I'm not completely certain that this captures all issues potentially
arising in the multi-node setup, but it should be fine for all-in-one.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* debug

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* conformance_tests: fix v2 vs v2.1 issues

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* opa: anything projects related is v2.1

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* server/migration: update engine store AFTER version to update is determined

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* engine/opa: remove partial result init on startup

The stores are empty -- any responses based on these will be wrong.
So, don't bother initializing.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* policy_refresher: force refresh when explicitly requested

...as when the version changes:

Without this flag, we'd get into the following situation when flipping
from v2 to v2.1 or vice-versa:

1. the server's state would flip (say, v2 -> v2.1)
2. the policy refresher would notice that nothing changed in the policy data
3. and hence would not update the engine store

as a result, the v2.1 engine store would remain non-functional.

This would lead to the `chef-automate iam upgrade-to-v2 --beta2.1` command
failing to list teams,

    APIError: An API error occurred during execution: Failed to retrieve
    team "editors": Failed to retrieve admins team: rpc error: code =
    PermissionDenied desc = error authorizing action "iam:teams:list" on
    resource "iam:teams" for subjects
    ["tls:service:deployment-service:40adf15d875d3190de6c24d0862804cf0d656be656f60234a8714a44563d5518"]:
    rpc error: code = Internal desc = error in query evaluation: cannot
    evaluate empty query

I'm not sure if this is the best way, or if the IAM version should be
reflected in the last change ID...

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* engine/opa: reset x and y if z has just been updated

This is a robustness measure -- without this, we might be answering the
wrong versioned queries when we really shouldn't.

Only relevant for scenarios where we upgrade, though, as usually, only
one of the three should be initialized on startup.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* engine/opa: cleanup V2SetPolicies vs V2p1SetPolicies

Plain v2 knows nothing about rules, and I think that's how it should
stay.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* authz-service/policy: move engine update below data migrations

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* policy_refresher: skip IAM v1 requests

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* policy_refresher: fix v2 vs v2.1 switch

yeah well if it's wrong it doesn't work.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* v2/policy_test: make this work with the separated version

On v2 server init, the version wasn't picked up: it depended on both the
version channel being non-nil, AND on the migration status NOT having
transitioned to failure. In the v2 memstore implementation, that was
possible.

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* policy_test: fix migration status change impact

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* Revert "engine/opa: cleanup V2SetPolicies vs V2p1SetPolicies"

This reverts commit 6f92330c4935cbb03c37ed5aa96402327338ca23.

Turns out the project rules stuff depends on this to work with IAM v2.

* Revert "opa: anything projects related is v2.1"

This reverts commit 54ca7bc2e3a630d92fcc3d638f66227ee845be52.

* policy_refresher: un-skip IAM v1 requests

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* Revert "engine/opa: reset x and y if z has just been updated"

This reverts commit f32a47682efd60a32aa5335dd25d046b935b65ed.

* opa: remove debug data dump

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* [integration]: update_reset_iam_v2: include v2.1, dedup script

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* ci: use --skip-policy-migration flag, not studio helper

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* add code comments per review comments

Signed-off-by: Stephan Renatus <srenatus@chef.io>

* authz-service: add note re: v2->v2.1 in multi-node

Signed-off-by: Stephan Renatus <srenatus@chef.io>