Post-upgrade compilation fix: LicenseStatus
$ ng build

ERROR in src/app/entities/license/license.model.ts:3:10 - error TS2440: Import declaration conflicts with local declaration of 'LicenseStatus'.

Signed-off-by: michael sorens <msorens@chef.io>