Bump automate UI from Angular 8 -> Angular 9 (#3082)
* Migration to Angular 9

Reference: https://next.angular.io/guide/updating-to-version-9

$ ng update @angular/core @angular/cli
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 74 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "9.0.5" (was "8.3.25")...
    Updating package.json with dependency @angular/core @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.900.5" (was "0.803.25")...
    Updating package.json with dependency @angular/language-service @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular-devkit/core @ "9.0.5" (was "8.3.25")...
    Updating package.json with dependency @angular-devkit/schematics @ "9.0.5" (was "8.3.25")...
    Updating package.json with dependency @angular/compiler-cli @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/animations @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency typescript @ "3.7.5" (was "3.5.3")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-server @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/compiler @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/forms @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/common @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency @angular/router @ "9.0.5" (was "8.2.14")...
    Updating package.json with dependency zone.js @ "0.10.2" (was "0.9.1")...
UPDATE package.json (4000 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

❯ Angular Workspace migration.
  Update an Angular CLI workspace to version 9.
    Package "@angular-devkit/schematics" found in the workspace package.json. This package typically does not need to be installed manually. If it is not being used by project code, it can be removed from the package.json.
    Package "@angular-devkit/core" found in the workspace package.json. This package typically does not need to be installed manually. If it is not being used by project code, it can be removed from the package.json.
UPDATE angular.json (5000 bytes)
UPDATE src/tsconfig.app.json (273 bytes)
UPDATE package.json (4000 bytes)
✔ Packages installed successfully.
  Migration completed.

❯ Lazy loading syntax migration.
  Update lazy loading syntax to use dynamic imports.
UPDATE src/app/app-routing.module.ts (10991 bytes)
  Migration completed.

❯ Replace deprecated 'styleext' and 'spec' Angular schematic options.
UPDATE angular.json (4997 bytes)
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ Static flag migration.
  Removes the `static` flag from dynamic queries.
  As of Angular 9, the "static" flag defaults to false and is no longer required for your view and content queries.
  Read more about this here: https://v9.angular.io/guide/migration-dynamic-flag
UPDATE src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts (8376 bytes)
  Migration completed.

❯ Missing @Injectable and incomplete provider definition migration.
  In Angular 9, enforcement of @Injectable decorators for DI is a bit stricter and incomplete provider definitions behave differently.
  Read more about this here: https://v9.angular.io/guide/migration-injectable
UPDATE src/app/helpers/history-selection/history-selection.ts (1538 bytes)
  Migration completed.

❯ ModuleWithProviders migration.
  In Angular 9, the ModuleWithProviders type without a generic has been deprecated.
  This migration adds the generic where it is missing.
  Read more about this here: https://v9.angular.io/guide/migration-module-with-providers
UPDATE src/app/pages/+compliance/shared/shared.module.ts (1195 bytes)
  Migration completed.

❯ Renderer to Renderer2 migration.
  As of Angular 9, the Renderer class is no longer available.
  Renderer2 should be used instead.
  Read more about this here: https://v9.angular.io/guide/migration-renderer
  Migration completed.

❯ Undecorated classes with decorated fields migration.
  As of Angular 9, it is no longer supported to have Angular field decorators on a class that does not have an Angular decorator.
  Read more about this here: https://v9.angular.io/guide/migration-undecorated-classes
  Migration completed.

❯ Undecorated classes with DI migration.
  As of Angular 9, it is no longer supported to use Angular DI on a class that does not have an Angular decorator.
  Read more about this here: https://v9.angular.io/guide/migration-undecorated-classes
  Migration completed.

Your project has been updated to Angular version 9!
For more info, please see: https://v9.angular.io/guide/updating-to-version-9

Signed-off-by: michael sorens <msorens@chef.io>

* Migration to Angular Material 9

$ ng update @angular/material
Using package manager: 'npm'
Collecting installed dependencies...
Found 74 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/material @ "9.1.1" (was "8.2.3")...
    Updating package.json with dependency @angular/cdk @ "9.1.1" (was "8.2.3")...
UPDATE package.json (3999 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/material' **

❯ Updates Angular Material to v9
    Could not find TypeScript project for project: automate-ui-e2e

    ⚠  General notice: The HammerJS v9 migration for Angular Components is not able to migrate tests. Please manually clean up tests in your project if they rely on HammerJS.
    Read more about migrating tests: https://git.io/ng-material-v9-hammer-migrate-tests

      ✓  Updated Angular Material to version 9

UPDATE src/app/page-components/delete-data-feed-dialog/delete-data-feed-dialog.component.ts (405 bytes)
UPDATE src/app/pages/data-feed/data-feed.component.ts (4183 bytes)
UPDATE src/app/pages/data-feed/data-feed.component.spec.ts (4235 bytes)
  Migration completed.

** Executing migrations of package '@angular/cdk' **

❯ Updates the Angular CDK to v9
    Could not find TypeScript project for project: automate-ui-e2e

      ✓  Updated Angular CDK to version 9

  Migration completed.

Signed-off-by: michael sorens <msorens@chef.io>

* Migration to @nguniversal 9

`npm outdated` now revealed this needed updating.

$ ng update @nguniversal/express-engine
Using package manager: 'npm'
Collecting installed dependencies...
Found 74 dependencies.
Fetching dependency metadata from registry...
                  Package "@nguniversal/express-engine" has a missing peer dependency of "express" @ "^4.15.2".
    Updating package.json with dependency @nguniversal/express-engine @ "9.0.1" (was "8.2.6")...
UPDATE package.json (3999 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@nguniversal/express-engine' **

❯ Update @nguniversal/express-engine to version 9.
UPDATE package.json (3999 bytes)
✔ Packages installed successfully.
  Migration completed.

Signed-off-by: michael sorens <msorens@chef.io>

* Post-upgrade lint: update deprecated method

Change TestBed.get -> TestBed.inject in 60 files

$ make lint
WARNING: /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/src/app/modules/team/team-details/team-details.component.spec.ts:225:22 - get is deprecated: from v9.0.0 use TestBed.inject
. . .

Signed-off-by: michael sorens <msorens@chef.io>

* Post-upgrade compilation fix: ModuleWithProviders

$ ng build

ERROR in src/app/pages/+compliance/shared/shared.module.ts:28:21 - error TS2304: Cannot find name 'ModuleWithProviders'.

28   static forRoot(): ModuleWithProviders<ComplianceSharedModule> {
                       ~~~~~~~~~~~~~~~~~~~

Signed-off-by: michael sorens <msorens@chef.io>

* Post-upgrade lint: fix quotes

$make lint

ERROR: /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/src/app/helpers/history-selection/history-selection.ts:3:28 - " should be '

Signed-off-by: michael sorens <msorens@chef.io>

* Update cdk-high-contrast overwrite

Fixes:

```
SassError: wrong number of arguments (2 for 1) for `cdk-high-contrast'
```

Signed-off-by: Scott Christopherson <scott@chef.io>

* Lock in package version due to bug

We were encountering this error from `ng build`:
```
ERROR in The target entry-point "ngx-cookie" has missing dependencies:
 - express-serve-static-core
```

The workaround is from this:
https://github.com/salemdar/ngx-cookie/issues/106

Signed-off-by: michael sorens <msorens@chef.io>

* Removing unneeded explicit dependencies

The angular upgrade indicated:
Package "@angular-devkit/schematics" found in the workspace package.json. This package typically does not need to be installed manually. If it is not being used by project code, it can be removed from the package.json.
Package "@angular-devkit/core" found in the workspace package.json. This package typically does not need to be installed manually. If it is not being used by project code, it can be removed from the package.json.

Signed-off-by: michael sorens <msorens@chef.io>

* Release the lock on ngrx packages to 8.x

This allows migrating them to 9.x

Signed-off-by: michael sorens <msorens@chef.io>

* Update ngrx to 9.0 and bump angular minor versions

$ npm update
+ @ngrx/store@9.0.0
+ @ngrx/store-devtools@9.0.0
+ @ngrx/router-store@9.0.0
+ @ngrx/effects@9.0.0
+ @ngrx/entity@9.0.0
updated 5 packages and audited 17029 packages in 12.309s
found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> @angular/cli@9.0.6 postinstall /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/@angular/cli
> node ./bin/postinstall/script.js

npm WARN ngx-cookie@4.1.2 requires a peer of @nguniversal/express-engine@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.3.4 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.

+ @angular/language-service@9.0.6
+ @angular/cli@9.0.6
+ @angular/common@9.0.6
+ @angular/animations@9.0.6
+ @angular/compiler-cli@9.0.6
+ @angular/platform-browser-dynamic@9.0.6
+ @angular/platform-browser@9.0.6
+ @angular/platform-server@9.0.6
+ @angular/forms@9.0.6
+ @angular/router@9.0.6
+ @angular/cdk@9.1.2
+ @angular/compiler@9.0.6
+ @angular/material@9.1.2
+ @angular-devkit/build-angular@0.900.6
+ @angular/core@9.0.6
updated 39 packages and audited 17029 packages in 100.993s

There was a warning about ngx-cookie, but that will be going away very soon:
npm WARN ngx-cookie@4.1.2 requires a peer of @nguniversal/express-engine@>=5.0.0 but none is installed. You must install peer dependencies yourself.

Signed-off-by: michael sorens <msorens@chef.io>

* npm audit fix

Signed-off-by: michael sorens <msorens@chef.io>

* Resync dependency changes in doc file

Signed-off-by: michael sorens <msorens@chef.io>

* Suppress DI deprecation warning in unit test output

Fixes:

```
WARN: 'DEPRECATED: DI is instantiating a token "MockLicenseFacadeService" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in v10. Please add @Injectable() to the "MockLicenseFacadeService" class.'
WARN: 'DEPRECATED: DI is instantiating a token "MockLicenseFacadeService" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in v10. Please add @Injectable() to the "MockLicenseFacadeService" class.'
WARN: 'DEPRECATED: DI is instantiating a token "MockLayoutFacadeService" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in v10. Please add @Injectable() to the "MockLayoutFacadeService" class.'
WARN: 'DEPRECATED: DI is instantiating a token "MockLayoutFacadeService" that inherits its @Injectable decorator but does not provide one itself.
This will become an error in v10. Please add @Injectable() to the "MockLayoutFacadeService" class.'
```

Signed-off-by: Scott Christopherson <scott@chef.io>

* Suppress layoutFacade ExpressionChangedAfterItHasBeenCheckedError

Trying out the `setTimeout` workaround described by others in https://github.com/angular/angular/issues/15634

Signed-off-by: Scott Christopherson <scott@chef.io>

* Update deprecated method name

WARNING: /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/src/app/entities/jobs/job.reducer.ts:28:35 - addAll is deprecated: addAll has been renamed. Use setAll instead.

Signed-off-by: michael sorens <msorens@chef.io>

Co-authored-by: michael sorens <msorens@users.noreply.github.com>
Co-authored-by: Scott Christopherson <scott@chef.io>