Angular 9 followup (#3230)
* Turn on template checking

Signed-off-by: michael sorens <msorens@chef.io>

* Fix mismatched function signature

error TS2554: Expected 0 arguments, but got 1
<input chefInput formControlName="newPassword" type="password" (keyup)="handlePasswordInput($event)" />

Signed-off-by: michael sorens <msorens@chef.io>

* Fix incompatible types

error TS2367: This condition will always return 'false' since the types 'CredentialTypes' and 'string' have no overlap.
<ng-container *ngIf="credential.type === 'ssh'">

Signed-off-by: michael sorens <msorens@chef.io>

* Cast AbstractControl to FormGroup

error TS2339: Property 'controls' does not exist on type 'AbstractControl'.
<div class="field" *ngIf="form.controls['end'].controls['include'].value">

Signed-off-by: michael sorens <msorens@chef.io>

* Add missing trackBy function

error TS2339: Property 'trackBy' does not exist on type 'SearchBarFilterBarComponent'.
<span *ngFor="let filter of filters; index as i; trackBy: trackBy;">

Signed-off-by: michael sorens <msorens@chef.io>

* Change symbol used in template to public

error TS2341: Property 'selectedStatus$' is private and only accessible within class 'ServiceGroupsComponent'.
<h3>None of the service groups returned {{ selectedStatus$ | async }}</h3>

Signed-off-by: michael sorens <msorens@chef.io>

* Accept Date type in datetime pipe

Handful of these errors due to feeding in a data type that was not present:

error TS2345: Argument of type 'Date' is not assignable to parameter of type 'string | Moment'.
    Run succeeded {{ nodeRun.endTime | datetime: RFC2822 }}

Signed-off-by: michael sorens <msorens@chef.io>

* Remove browser warning

This browser console warning occurs on DataFeed page and Notifications page:

 core.js:12557 Can't bind to 'contrasting-background' since it isn't a known property of 'chef-page-header'.

Signed-off-by: michael sorens <msorens@chef.io>

* Correct invalid expression

error TS2365: Operator '>' cannot be applied to types 'boolean' and 'number'.
50       <li *ngIf="inputText !== '' && delayForNoSuggestions && !filterValues.length > 0" class="no-category-items">

Signed-off-by: michael sorens <msorens@chef.io>

* Add types for animation in policy-add-members (#3180)

Signed-off-by: seajamied <jdegnan@chef.io>

* Event feed guitar strings template error

The incorrect type of parameter was being passed to the zoombutton.

Signed-off-by: Lance Finfrock <lfinfrock@chef.io>

* Jamie/angular 9 followup fixes 2 (#3189)

* Fix status type on reporting component

Signed-off-by: seajamied <jdegnan@chef.io>

* Add types to reporting summary

Signed-off-by: seajamied <jdegnan@chef.io>

* Add disconnected group to initial model and type for disconnected services

Signed-off-by: seajamied <jdegnan@chef.io>

* Add stronger typing to report data service and reporting component

Signed-off-by: seajamied <jdegnan@chef.io>

* Inprove import and add more strong typing

Signed-off-by: seajamied <jdegnan@chef.io>

* Follow-on unit test fixes

Signed-off-by: michael sorens <msorens@chef.io>

* Fix failing job-form e2e specs

Signed-off-by: Scott Christopherson <scott@chef.io>

Co-authored-by: Jamie D <jamie.degnan@gmail.com>
Co-authored-by: Lance Finfrock <lfinfrock@chef.io>
Co-authored-by: Scott Christopherson <scott@chef.io>