Remove separate @types/diff2html package
Apparently the type signatures are now built-in to the main package,
so this separate set of type definitiions is no longer needed.

Resolves this error in `make serve`:

  ERROR in ../node_modules/@types/diff2html/index.d.ts:70:14 - error TS2300: Duplicate identifier 'd2h'.
  70     export = d2h;
  ../node_modules/diff2html/src/diff2html.d.ts:70:12
    70   export = d2h;
    'd2h' was also declared here.

Signed-off-by: michael sorens <msorens@chef.io>