Code coverage fix due to Angular upgrade
Code coverage fails to run if ui-lib assets are not installed.
This same issue was fixed for the main build previously
on commit b4042b3d1923c15f1262ef60ac1cc6d60454c041.

Error Text:
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find 'assets/chef-ui-library/chef/chef.css'
  in [
    /workdir/components/automate-ui/src
  ]
    at resolveModule.catch.catch (/workdir/components/automate-ui/node_modules/postcss-import/lib/resolve-id.js:35:13)
 @ ./src/styles.scss 1:14-241
 @ multi ./src/styles.scss
```

Signed-off-by: michael sorens <msorens@chef.io>