Fix incompatible types
error TS2367: This condition will always return 'false' since the types 'CredentialTypes' and 'string' have no overlap.
<ng-container *ngIf="credential.type === 'ssh'">

Signed-off-by: michael sorens <msorens@chef.io>