[automate-2576] Bump npm versions (#2576)
* Bump to latest Angular 8

$ ng update @angular/core@8 @angular/cli@8
Using package manager: 'npm'
Collecting installed dependencies...
Found 75 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "8.3.21" (was "8.3.6")...
    Updating package.json with dependency @angular/core @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.803.21" (was "0.803.6")...
    Updating package.json with dependency @angular/language-service @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/compiler-cli @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/common @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/compiler @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/platform-browser @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/animations @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/router @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/platform-server @ "8.2.14" (was "8.2.8")...
    Updating package.json with dependency @angular/forms @ "8.2.14" (was "8.2.8")...
UPDATE package.json (4022 bytes)

> fsevents@1.2.11 install /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/@angular/compiler-cli/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/webpack-dev-server/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> @angular/cli@8.3.21 postinstall /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/@angular/cli
> node ./bin/postinstall/script.js

> automate-ui@0.0.0 install /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> echo 'use `npm run install:ui-library` for old behaviour'; npm run copy-ui-lib

use `npm run install:ui-library` for old behaviour

> automate-ui@0.0.0 copy-ui-lib /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> npm run copy-ui-lib:library && npm run copy-ui-lib:fonts

> automate-ui@0.0.0 copy-ui-lib:library /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> cp -r ../chef-ui-library/dist/ src/assets/chef-ui-library

> automate-ui@0.0.0 copy-ui-lib:fonts /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> cp -r ../chef-ui-library/dist/collection/assets/fonts/ src/assets/fonts

added 145 packages from 53 contributors, removed 2 packages, updated 199 packages and audited 18033 packages in 113.208s
found 0 vulnerabilities

Signed-off-by: michael sorens <msorens@chef.io>

* Bump remaining angular packages as well

$ ng update @angular-devkit/core @angular-devkit/schematics @angular/cdk @angular/material
Using package manager: 'npm'
Collecting installed dependencies...
Found 75 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/core @ "8.3.21" (was "8.3.6")...
    Updating package.json with dependency @angular-devkit/schematics @ "8.3.21" (was "8.3.6")...
    Updating package.json with dependency @angular/cdk @ "8.2.3" (was "8.2.1")...
    Updating package.json with dependency @angular/material @ "8.2.3" (was "8.2.1")...
UPDATE package.json (4024 bytes)

> automate-ui@0.0.0 install /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> echo 'use `npm run install:ui-library` for old behaviour'; npm run copy-ui-lib

use `npm run install:ui-library` for old behaviour

> automate-ui@0.0.0 copy-ui-lib /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> npm run copy-ui-lib:library && npm run copy-ui-lib:fonts

> automate-ui@0.0.0 copy-ui-lib:library /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> cp -r ../chef-ui-library/dist/ src/assets/chef-ui-library

> automate-ui@0.0.0 copy-ui-lib:fonts /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui
> cp -r ../chef-ui-library/dist/collection/assets/fonts/ src/assets/fonts

updated 5 packages and audited 18033 packages in 36.702s
found 0 vulnerabilities

Signed-off-by: michael sorens <msorens@chef.io>

* Bump ngrx packages

$ npm update @ngrx/effects @ngrx/entity @ngrx/router-store @ngrx/store  @ngrx/store-devtools
+ @ngrx/store-devtools@8.6.0
+ @ngrx/store@8.6.0
+ @ngrx/effects@8.6.0
+ @ngrx/entity@8.6.0
+ @ngrx/router-store@8.6.0
updated 5 packages and audited 18033 packages in 11.958s
found 0 vulnerabilities

Signed-off-by: michael sorens <msorens@chef.io>

* Bump remaining, non-constrained packages

$ npm update
npm WARN rm not removing /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/.bin/karma as it wasn't installed by /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/karma

> node-sass@4.13.0 install /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/darwin-x64-64_binding.node
Download complete
Binary saved to /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/msorens/.npm/node-sass/4.13.0/darwin-x64-64_binding.node

> core-js@3.2.1 postinstall /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/@angular-devkit/build-angular/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.0 postinstall /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> node-sass@4.13.0 postinstall /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/msorens/code/go/src/github.com/chef/automate/components/automate-ui/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
+ @nguniversal/express-engine@8.2.6
+ codelyzer@5.2.1
+ d3@5.14.2
+ @types/faker@4.1.8
+ core-js@3.6.0
+ karma@4.4.1
+ @types/lodash@4.14.149
+ node-sass@4.13.0
+ @types/node@10.17.11
+ diff2html@2.12.1
+ tslint@5.20.1
+ karma-coverage-istanbul-reporter@2.1.1
+ ts-node@8.5.4
added 1 package from 1 contributor, removed 29 packages, updated 46 packages, moved 1 package and audited 18031 packages in 25.267s
found 0 vulnerabilities

Signed-off-by: michael sorens <msorens@chef.io>

* Remove separate @types/diff2html package

Apparently the type signatures are now built-in to the main package,
so this separate set of type definitiions is no longer needed.

Resolves this error in `make serve`:

  ERROR in ../node_modules/@types/diff2html/index.d.ts:70:14 - error TS2300: Duplicate identifier 'd2h'.
  70     export = d2h;
  ../node_modules/diff2html/src/diff2html.d.ts:70:12
    70   export = d2h;
    'd2h' was also declared here.

Signed-off-by: michael sorens <msorens@chef.io>

* Update @types/jasminewd2

Formerly constrained version on this package.
Now an update generates no errors from build, test, or e2e.

Signed-off-by: michael sorens <msorens@chef.io>

* Adjust @types/node to sync with node version

We are currently on node 10.15.2.
The latest @types/node less than that is 10.14.22,
so updating to that.

Signed-off-by: michael sorens <msorens@chef.io>

* readme updates

Signed-off-by: michael sorens <msorens@chef.io>