Accept Date type in datetime pipe
Handful of these errors due to feeding in a data type that was not present:

error TS2345: Argument of type 'Date' is not assignable to parameter of type 'string | Moment'.
    Run succeeded {{ nodeRun.endTime | datetime: RFC2822 }}

Signed-off-by: michael sorens <msorens@chef.io>