policy_refresher: force refresh when explicitly requested
...as when the version changes:

Without this flag, we'd get into the following situation when flipping
from v2 to v2.1 or vice-versa:

1. the server's state would flip (say, v2 -> v2.1)
2. the policy refresher would notice that nothing changed in the policy data
3. and hence would not update the engine store

as a result, the v2.1 engine store would remain non-functional.

This would lead to the `chef-automate iam upgrade-to-v2 --beta2.1` command
failing to list teams,

    APIError: An API error occurred during execution: Failed to retrieve
    team "editors": Failed to retrieve admins team: rpc error: code =
    PermissionDenied desc = error authorizing action "iam:teams:list" on
    resource "iam:teams" for subjects
    ["tls:service:deployment-service:40adf15d875d3190de6c24d0862804cf0d656be656f60234a8714a44563d5518"]:
    rpc error: code = Internal desc = error in query evaluation: cannot
    evaluate empty query

I'm not sure if this is the best way, or if the IAM version should be
reflected in the last change ID...

Signed-off-by: Stephan Renatus <srenatus@chef.io>