Add missing trackBy function
error TS2339: Property 'trackBy' does not exist on type 'SearchBarFilterBarComponent'.
<span *ngFor="let filter of filters; index as i; trackBy: trackBy;">

Signed-off-by: michael sorens <msorens@chef.io>